language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: OcmbJshQx7Zn/VLKdrK+tURk3RhJJ1felwlMhZUJVAEajhjOAHjcEyK8RN9hP7OlQ7Q5Z2tT4xt/INh6gM117+1FhnyvVu0Zt8BOKjKaYxkKhkRpPPkopm9nxYDNh3OhZ1DrkiRVRWdhCIfzDm/0SePCxyblSd+5M7m/2hnny/bCFIui0KbOH3oObDZOg6UTkQOIdYl7h4X2q/+8uWwUXDXI9JZ+Hck53FLAtdVh+Nrs4yrnsv3BM5ue74EOuByp8K0jErYnW04N6CS/5phYnb7pWSKoWgxhSsuCuGCqz8x7Fud8Ii3KRleIKug3vsCT0sPONy4y2qk6dcj0r42HUhS+JwrXhOfWm84uuxN+9ztlvKMwCdLg+SBNJ+SOgadXgjj7+TP2uVWtWIdguZwGnLWWr7xbIAQ+uztwH5XCbhye7Amy2/2g7gPMPgOarqvwTwt5EESuZe2RtZjZAUKZm796Lg6wgTKoBKyS672nIXBQPVZpwTRbbrvzWpo5ydn0uTGmRcNk3Pq4YTqP4j/USeIdzDAonSUJo40bR4RtQuipdfTwTfv84zFSIUYHt3ScVGZnuJAeriHXUoNrlNERsACzglK2IN5vvm2D028BokIqsclsLGyU7GDnngG2aJCep3ZitnS1vFZlwTMX/lUPDbybnl1+lJwKMdXwUNXNe1g=
